---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: app1
    run_list: recipe[config-test::app1]
    attributes:
  - name: app2
    run_list: recipe[config-test::app2]
    attributes:
  - name: both
    run_list:
      - recipe[config-test::app1]
      - recipe[config-test::app2]
    attributes:
